### ISSUE TITLE
RetCode not Retcode!!!

### ISSUE THREAD

**Issue by XLILT** [KscSDK/ksc-sdk-java#185]
--- a/ksc-sdk-java-kls/src/main/java/com/ksc/kls/model/ParamConstant.java
+++ b/ksc-sdk-java-kls/src/main/java/com/ksc/kls/model/ParamConstant.java
@@ -26,7 +26,8 @@ public class ParamConstant {
 
     public static final String RECID = "RecID";
 
-    public static final String RETCODE = "Retcode";
+    // public static final String RETCODE = "Retcode";
+    public static final String RETCODE = "RetCode";
 
     public static final String RETMSG = "RetMsg";

你们现在版本SDK的返回码key值是Retcode，而金山云服务目前是RetCode。请尽快核实并提交新版本jar包到阿里云仓库，谢谢！！！

**Comment by xuyaming0800** [comment]
我们的发布在maven公服 不在阿里云仓库
