### ISSUE TITLE
sbt无法下载资源

### ISSUE THREAD

**Issue by mirszhao** [KscSDK/ksc-sdk-java#61]
io problem while parsing ivy file: http://repo1.maven.org/maven2/com/ksyun/ksc-sdk-java-core/0.2.0/ksc-sdk-java-core-0.2.0.pom: Impossible to load parent for file:/C:/Users/admin/.ivy2/cache/com.ksyun/ksc-sdk-java-core/ivy-0.2.0.xml.original. Parent=com.ksyun#ksc-sdk-java;0.2.0

**Comment by xuyaming0800** [comment]
fixed
